In [129]:
import pandas as pd
import numpy as np

### Importing Original data of past retirements

In [130]:
odf=pd.read_csv('ds_data2.csv')

In [131]:
odf

,Unnamed: 0,FacultyId,Name,Gender,Age,JoiningYear,Designation,AreaOfSpecialization,AppointmentType,EndYear,EndMonth
0,0,0,Joanna Smith,Female,54,2006,Director,Data Science and Engineering,Approve,2022,June
1,1,1,Bradley Johnson,Male,47,2008,Senior Professor,Environmental Engineering,Regular,2022,June
2,2,2,Alexander Wilkinson,Female,60,2003,Research Professor,Civil Engineering,Approve,2022,July
3,3,3,Kayla Nixon,Female,51,2007,Research Professor,Aerospace Engineering,Approve,2022,June
4,4,4,Joseph King,Female,42,2010,Director,Civil Engineering,Regular,2022,May
...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,9995,Diane Thomas,Male,45,2003,Associate Professor,Chemical Engineering,Conract,2016,May
9996,9996,9996,Katie Harvey,Female,47,2002,Assistant professor,Software Engineering,Conract,2016,June
9997,9997,9997,Jodi Horton,Female,58,1999,Assistant professor,Environmental Engineering,Regular,2016,July
9998,9998,9998,Brittany Hicks,Male,50,2001,Senior Professor,Chemical Engineering,Regular,2016,June
9999,9999,9999,Dustin Rodriguez,Female,60,1996,Research Professor,Software Engineering,Approve,2016,August

### Feature Engineering for regression fitting

In [132]:
df=odf.drop(['Unnamed: 0', 'FacultyId', 'Name'], axis=1)

#### Splitting into features and dependent

In [133]:
x1 = df.iloc[:, :-2]
x1['EndMonth']= odf['EndMonth']
y = df.iloc[:, 6]  # Dependent variable

### Encoding

In [134]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x1['DesignationEC'] = label_encoder.fit_transform(x1['Designation'])
x1['AreaOfSpecializationEC'] = label_encoder.fit_transform(x1['AreaOfSpecialization'])
x1['GenderEC'] = label_encoder.fit_transform(x1['Gender'])
x1['AppointmentTypeEC'] = label_encoder.fit_transform(x1['AppointmentType'])

In [135]:
x=x1.drop(['Gender','Designation','AreaOfSpecialization','AppointmentType','EndMonth'],axis=1)

### Data Splitting for training and testing

In [136]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
# Assume you have features 'x' and target variable 'y'
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

#### Linear regression model

In [137]:
# Create a linear regression model
regressor = LinearRegression()

# Fit the model to the training data
regressor.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = regressor.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)

### Mean standard error in our prediction model

In [138]:
mse

1.1409271359185604

#### Converting predicted values into whole numbers ( as they represent years)

In [139]:
import math
y_pred1=[]
for i in y_pred:
    y_pred1.append(math.floor(i))

In [140]:
from sklearn.metrics import accuracy_score

# Assuming you have predicted values y_pred and true values y_test
accuracy = accuracy_score(y_test, y_pred1)
accuracy

0.272

## Using our model

In [141]:
ndf=pd.read_csv('dataForPrediction.csv')

In [142]:
ndf

,Unnamed: 0,FacultyId,Name,Gender,Age,JoiningYear,Designation,AreaOfSpecialization,AppointmentType
0,0,0,Emma Scott MD,Female,54,2018,Dean,Data Science and Engineering,Regular
1,1,1,Henry Lewis,Male,47,2022,Research Professor,Robotics and Automation,Regular
2,2,2,Rachael Green,Female,60,2017,Research Professor,Electrical Engineering,Conract
3,3,3,Donna Brown MD,Female,51,2017,Lecturer,Geotechnical Engineering,Approve
4,4,4,Crystal Lambert,Male,42,2022,Senior Professor,Aerospace Engineering,Regular
...,...,...,...,...,...,...,...,...,...
995,995,995,Sylvia Miller,Female,57,2016,Senior Professor,Geotechnical Engineering,Regular
996,996,996,James Carroll,Female,52,2018,Director,Data Science and Engineering,Conract
997,997,997,Jessica Collins,Female,60,2016,Assistant professor,Robotics and Automation,Regular
998,998,998,Debra Glenn,Female,51,2018,Assistant professor,Aerospace Engineering,Approve
999,999,999,Danielle Davis,Male,60,2018,Director,Mechanical Engineering,Regular

In [143]:
x2=ndf.drop(['Unnamed: 0', 'FacultyId', 'Name'], axis=1)
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
#x2['EndMonthEC'] = label_encoder.fit_transform(x2['EndMonth'])
x2['DesignationEC'] = label_encoder.fit_transform(x2['Designation'])
x2['AreaOfSpecializationEC'] = label_encoder.fit_transform(x2['AreaOfSpecialization'])
x2['GenderEC'] = label_encoder.fit_transform(x2['Gender'])
x2['AppointmentTypeEC'] = label_encoder.fit_transform(x2['AppointmentType'])
y=x2.drop(['Gender','Designation','AreaOfSpecialization','AppointmentType'],axis=1)

In [144]:
final_pred = regressor.predict(y)
final_pred1=[]
for i in final_pred:
    final_pred1.append(math.floor(i))

### Final Predicted Years

In [145]:
final_pred1

[2030,
 2030,
 2031,
 2028,
 2028,
 2031,
 2028,
 2032,
 2031,
 2032,
 2031,
 2032,
 2031,
 2030,
 2031,
 2031,
 2029,
 2029,
 2030,
 2029,
 2031,
 2032,
 2030,
 2025,
 2029,
 2029,
 2030,
 2032,
 2030,
 2031,
 2030,
 2029,
 2032,
 2032,
 2025,
 2032,
 2028,
 2030,
 2029,
 2027,
 2025,
 2031,
 2028,
 2028,
 2029,
 2031,
 2030,
 2031,
 2028,
 2030,
 2027,
 2031,
 2029,
 2030,
 2031,
 2030,
 2030,
 2031,
 2024,
 2028,
 2031,
 2030,
 2031,
 2030,
 2028,
 2032,
 2030,
 2030,
 2030,
 2028,
 2032,
 2030,
 2028,
 2030,
 2028,
 2032,
 2025,
 2027,
 2029,
 2029,
 2030,
 2026,
 2029,
 2029,
 2031,
 2030,
 2032,
 2030,
 2030,
 2030,
 2025,
 2029,
 2029,
 2027,
 2028,
 2030,
 2030,
 2032,
 2031,
 2027,
 2029,
 2031,
 2029,
 2031,
 2032,
 2029,
 2032,
 2029,
 2031,
 2031,
 2030,
 2032,
 2030,
 2031,
 2032,
 2031,
 2024,
 2029,
 2030,
 2024,
 2031,
 2030,
 2030,
 2027,
 2030,
 2029,
 2030,
 2028,
 2030,
 2030,
 2030,
 2031,
 2024,
 2031,
 2029,
 2031,
 2027,
 2032,
 2029,
 2031,
 2029,
 2029,
 2031,
 2030,
 2026,
 2029,
 2031,
 2030,
 2029,
 2030,
 2025,
 2028,
 2030,
 2028,
 2028,
 2031,
 2031,
 2030,
 2032,
 2031,
 2029,
 2027,
 2030,
 2029,
 2028,
 2030,
 2029,
 2027,
 2029,
 2032,
 2032,
 2026,
 2031,
 2028,
 2029,
 2028,
 2030,
 2027,
 2030,
 2031,
 2029,
 2030,
 2031,
 2028,
 2027,
 2030,
 2032,
 2032,
 2031,
 2030,
 2030,
 2026,
 2028,
 2032,
 2027,
 2031,
 2028,
 2031,
 2030,
 2031,
 2032,
 2030,
 2032,
 2028,
 2032,
 2030,
 2025,
 2029,
 2031,
 2025,
 2031,
 2031,
 2032,
 2031,
 2023,
 2025,
 2031,
 2027,
 2030,
 2029,
 2028,
 2031,
 2029,
 2029,
 2030,
 2031,
 2030,
 2031,
 2029,
 2030,
 2029,
 2031,
 2030,
 2030,
 2029,
 2030,
 2030,
 2031,
 2028,
 2031,
 2031,
 2024,
 2030,
 2030,
 2031,
 2029,
 2030,
 2030,
 2029,
 2029,
 2030,
 2026,
 2030,
 2030,
 2030,
 2030,
 2028,
 2030,
 2031,
 2032,
 2031,
 2028,
 2027,
 2030,
 2032,
 2029,
 2029,
 2030,
 2029,
 2029,
 2030,
 2032,
 2028,
 2030,
 2029,
 2031,
 2029,
 2030,
 2030,
 2030,
 2032,
 2031,
 2029,
 2027,
 2029,
 2027,
 2032,
 2030,
 2023,
 2029,
 2031,
 2026,
 2025,
 2029,
 2030,
 2029,
 2028,
 2028,
 2027,
 2026,
 2029,
 2032,
 2031,
 2032,
 2031,
 2027,
 2031,
 2032,
 2028,
 2030,
 2030,
 2025,
 2030,
 2031,
 2031,
 2030,
 2031,
 2026,
 2031,
 2031,
 2027,
 2029,
 2030,
 2029,
 2029,
 2029,
 2030,
 2031,
 2030,
 2028,
 2029,
 2029,
 2032,
 2028,
 2025,
 2029,
 2030,
 2032,
 2030,
 2030,
 2031,
 2032,
 2030,
 2026,
 2031,
 2032,
 2030,
 2030,
 2030,
 2032,
 2031,
 2028,
 2031,
 2030,
 2030,
 2032,
 2030,
 2029,
 2030,
 2029,
 2030,
 2032,
 2030,
 2031,
 2028,
 2031,
 2030,
 2031,
 2029,
 2032,
 2030,
 2030,
 2032,
 2027,
 2031,
 2031,
 2030,
 2031,
 2029,
 2030,
 2032,
 2030,
 2030,
 2028,
 2029,
 2027,
 2030,
 2026,
 2028,
 2030,
 2028,
 2029,
 2031,
 2031,
 2031,
 2029,
 2030,
 2031,
 2031,
 2032,
 2032,
 2029,
 2032,
 2030,
 2029,
 2030,
 2029,
 2028,
 2032,
 2030,
 2029,
 2031,
 2029,
 2031,
 2032,
 2030,
 2029,
 2032,
 2030,
 2031,
 2027,
 2030,
 2029,
 2029,
 2031,
 2031,
 2030,
 2029,
 2031,
 2030,
 2030,
 2028,
 2031,
 2029,
 2031,
 2027,
 2030,
 2032,
 2030,
 2030,
 2030,
 2029,
 2026,
 2032,
 2032,
 2031,
 2029,
 2030,
 2030,
 2030,
 2031,
 2028,
 2029,
 2031,
 2029,
 2028,
 2030,
 2027,
 2030,
 2031,
 2028,
 2030,
 2032,
 2031,
 2031,
 2030,
 2029,
 2030,
 2031,
 2028,
 2030,
 2029,
 2030,
 2030,
 2032,
 2029,
 2028,
 2030,
 2031,
 2028,
 2031,
 2032,
 2031,
 2029,
 2031,
 2030,
 2030,
 2030,
 2028,
 2029,
 2030,
 2030,
 2032,
 2029,
 2028,
 2030,
 2029,
 2031,
 2030,
 2028,
 2031,
 2030,
 2027,
 2030,
 2032,
 2030,
 2025,
 2028,
 2030,
 2027,
 2032,
 2030,
 2028,
 2031,
 2025,
 2029,
 2029,
 2030,
 2030,
 2029,
 2031,
 2029,
 2028,
 2030,
 2030,
 2032,
 2028,
 2029,
 2029,
 2031,
 2030,
 2031,
 2031,
 2032,
 2030,
 2032,
 2030,
 2027,
 2032,
 2029,
 2031,
 2027,
 2032,
 2029,
 2031,
 2031,
 2029,
 2030,
 2029,
 2030,
 2029,
 2030,
 2030,
 2032,
 2031,
 2026,
 2027,
 2027,
 2031,
 2029,
 2028,
 2029,
 2031,
 2031,
 2030,
 2030,
 2029,
 2028,
 2030,
 2030,
 2031,
 2030,
 2032,
 2030,
 2030,
 2028,
 2028,
 2028,
 2028,
 2030,
 2030,
 2023,
 2030,
 2027,
 2030,
 2028,
 2028,
 2029,
 2030,
 2028,
 2030,
 2030,
 2030,
 2030,
 2030,
 2030,
 2029,
 2028,
 2029,
 2031,
 2027,
 2029,
 2031,
 2031,
 2031,
 2028,
 2030,
 2029,
 2029,
 2032,
 2029,
 2030,
 2030,
 2028,
 2030,
 2029,
 2028,
 2030,
 2031,
 2028,
 2029,
 2029,
 2029,
 2031,
 2030,
 2029,
 2028,
 2029,
 2029,
 2031,
 2030,
 2030,
 2027,
 2029,
 2024,
 2030,
 2031,
 2027,
 2030,
 2029,
 2030,
 2031,
 2031,
 2029,
 2027,
 2024,
 2030,
 2030,
 2030,
 2029,
 2029,
 2031,
 2030,
 2032,
 2029,
 2028,
 2029,
 2025,
 2029,
 2030,
 2031,
 2031,
 2031,
 2027,
 2028,
 2031,
 2030,
 2030,
 2028,
 2028,
 2027,
 2029,
 2031,
 2025,
 2030,
 2028,
 2029,
 2032,
 2032,
 2031,
 2028,
 2029,
 2029,
 2029,
 2024,
 2032,
 2031,
 2030,
 2031,
 2030,
 2030,
 2028,
 2031,
 2030,
 2030,
 2030,
 2030,
 2030,
 2030,
 2031,
 2031,
 2029,
 2030,
 2025,
 2032,
 2027,
 2025,
 2028,
 2029,
 2029,
 2028,
 2028,
 2030,
 2028,
 2026,
 2031,
 2029,
 2032,
 2028,
 2029,
 2030,
 2030,
 2029,
 2030,
 2029,
 2028,
 2028,
 2027,
 2030,
 2029,
 2030,
 2030,
 2031,
 2030,
 2032,
 2027,
 2024,
 2031,
 2030,
 2031,
 2025,
 2029,
 2031,
 2032,
 2032,
 2032,
 2030,
 2032,
 2028,
 2032,
 2028,
 2030,
 2030,
 2028,
 2031,
 2023,
 2032,
 2031,
 2029,
 2029,
 2031,
 2031,
 2028,
 2030,
 2031,
 2030,
 2030,
 2030,
 2028,
 2027,
 2029,
 2030,
 2029,
 2024,
 2032,
 2029,
 2032,
 2028,
 2027,
 2031,
 2030,
 2027,
 2032,
 2027,
 2031,
 2031,
 2031,
 2032,
 2031,
 2031,
 2030,
 2028,
 2030,
 2032,
 2027,
 2029,
 2032,
 2031,
 2031,
 2026,
 2028,
 2032,
 2029,
 2027,
 2032,
 2029,
 2032,
 2031,
 2024,
 2030,
 2030,
 2030,
 2030,
 2031,
 2028,
 2030,
 2027,
 2026,
 2031,
 2031,
 2028,
 2031,
 2030,
 2027,
 2030,
 2028,
 2027,
 2028,
 2029,
 2031,
 2032,
 2031,
 2029,
 2028,
 2028,
 2030,
 2030,
 2026,
 2030,
 2030,
 2030,
 2031,
 2028,
 2031,
 2029,
 2031,
 2030,
 2030,
 2030,
 2025,
 2028,
 2030,
 2030,
 2029,
 2030,
 2029,
 2029,
 2031,
 2031,
 2029,
 2030,
 2029,
 2028,
 2030,
 2031,
 2031,
 2031,
 2029,
 2029,
 2030,
 2030,
 2027,
 2027,
 2029,
 2029,
 2031,
 2031,
 2032,
 2031,
 2028,
 2030,
 2029,
 2032,
 2032,
 2028,
 2029,
 2025,
 2028,
 2028,
 2027,
 2031,
 2028,
 2030,
 2028,
 2029,
 2031,
 2031,
 2030,
 2030,
 2028,
 2032,
 2029,
 2030,
 2032,
 2031,
 2027,
 2030,
 2023,
 2029,
 2031,
 2030,
 2029,
 2027,
 2028,
 2028,
 2030,
 2030,
 2031,
 2030,
 2030,
 2031,
 2029,
 2030,
 2031,
 2029,
 2031,
 2030,
 2030,
 2032,
 2031,
 2028,
 2031,
 2025,
 2030,
 2030,
 2029,
 2030,
 2030,
 2029,
 2031,
 2030,
 2023,
 2029,
 2027,
 2027,
 2028,
 2027,
 2031,
 2027,
 2030,
 2023,
 2030,
 2028,
 2030,
 2030,
 2028,
 2031,
 2031,
 2030,
 2031,
 2029,
 2032,
 2032,
 2029,
 2029,
 2030,
 2030,
 2027,
 2030,
 2030,
 2029,
 2028,
 2030,
 2031,
 2030,
 2026,
 2030,
 2030,
 2029,
 2030,
 2030,
 2031,
 2028,
 2031,
 2027,
 2030,
 2030,
 2028,
 2029,
 2031,
 2028,
 2029,
 2028,
 2031,
 2026,
 2029,
 2029,
 2030,
 2029,
 2032]

### Return count of potential vacancies in 2024

In [ ]:
curr_year =2024
vacancies=0
for i in final_pred1: